# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.159.0+26.2

# Mod Properties
mod_version = 2.2.0-26.2
maven_group = cn.blockforge.generated.briefguard
archives_base_name = brief_guard
